<?php

namespace Symfony\Cmf\Bundle\RoutingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExternalRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalRouteRepository extends EntityRepository
{
}
